# Generated by Django 3.1.6 on 2021-02-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210207_0437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
