# Generated by Django 3.1.6 on 2021-02-15 02:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210215_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000, verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=150, verbose_name='your comment:'),
        ),
    ]
