# Generated by Django 3.1.6 on 2021-02-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.svg', upload_to='avatars/%Y/%m/%d'),
        ),
    ]
