# Generated by Django 3.1.6 on 2021-02-16 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_profile_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=200, unique=True),
        ),
    ]
