# Generated by Django 3.1.6 on 2021-02-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20210216_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_id',
        ),
    ]
