# Generated by Django 3.1.6 on 2021-02-13 17:52

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0010_auto_20210209_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ManyToManyField(to='profiles.Profile')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='profiles.profile')),
            ],
        ),
    ]
