# Generated by Django 3.1.6 on 2021-02-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210209_0840'),
        ('direct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ManyToManyField(related_name='recipient', to='profiles.Profile'),
        ),
    ]
